#!/bin/bash

# Cliente de telnet para conectarse al servidor DFS
# Sintaxis:
# ./dfs_client [PORT] [ESC_CHAR]

DEF_ECHR=+
DEF_PORT=8000

PORT=${1:-$DEF_PORT}
ECHR=${2:-$DEF_ECHR}

telnet -e $ECHR localhost $PORT
